__author__ = 'leena'


def get_template_name(category):
    return {"space_progress": "space_progress_email",
            "space_status_change": "space_status_change",
            "space_status_complete": "space_status_complete",
            "space_cityadd": "space_cityadd",
            "space_new" : 'space_new',
            "enquiry_space": "enq_space",
            "enquiry_reply":"enq_reply",
            "enquiry_status": "enq_status",
            "enquiry_closed":"enq_closed",
            "enquiry_accept":"enq_accept",
            "enquiry_reject":"enq_reject",
            "enquiry_created": "enq_created",
            "enquiry_noreply": "enq_noreply",
            "book_new": "book_new",
            "book_accept": "book_accept",
            "book_reject": "book_reject",
            "book_reminder": "book_reminder",
            "book_cancel": "book_cancel",
            "book_cancel_approve": "book_cancel_approve",
            "book_cancel_disapp": "book_cancel_disapp",
            "book_cancel_request" :"book_cancel_req",
            "book_incomp_reminder": "book_incomp_rem",
            "book_receipt": "book_receipt",
            "book_invite": "book_invite",
            "book_meet_cancel": "book_meet_cancel",
            "book_noreply": "book_noreply",
            "requirement_created": "req_created",
            "requirement_reminder": "req_reminder",
            "requirement_suggestion": "req_suggestion",
            "requirement_new": "req_new",
            "requirement_reply": "req_reply",
            "requirement_noreply": "req_noreply",
            "revoke_space": "revoke_space",
            "space_awaited_approval": "space_await_approval",
            "feedback_space": "feedback_space",
            "feedback_system": "feedback_system",
            "change_password": "change_pwd",
            "forgot_password": "forgot_pwd",
            "invite_referral": "invite_referral",
            "new_booking": "new_booking",
            "signup": "signup",
            "space_add":"space_add",
            "transaction_progress" :"transact_progress"
    }[category]

